CVBuild/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('form.urls')),
]

form/urls.py
from django.urls import path
from .views import create_cv, PreviewCV, export_pdf,save_to_json, import_json_to_form,form_view

app_name = 'app_form'

urlpatterns = [
    path('', create_cv, name='create_cv'),
    path('preview/<slug:slug>/', PreviewCV.as_view(), name='preview'),
    path('export/<int:cv_id>/', export_pdf, name='export_pdf'),
    path('savejson/<slug:slug>/',save_to_json,name='savejson'),
    path('upload-json-form/', import_json_to_form, name='upload_json_form'),
    path('form/', form_view, name='form_view'),
]

templates/snippets/title.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top bg-primary">
  <div class="container">
    <img src="{% static 'img/logo.png' %}" alt="">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app_form:create_cv' %}">Home</a>
        </li>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Go to </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="">Personal Information</a></li>
            <li><a class="dropdown-item" href="#education">Education</a></li>
            <li><a class="dropdown-item" href="#skill">Skill</a></li>
            <li><a class="dropdown-item" href="#experience">Work Experience</a></li>
            <li><a class="dropdown-item" href="#certificate">Certificate</a></li>
            <li><a class="dropdown-item" href="#submit-button">Submit Button</a></li>
            
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>